### ISSUE TITLE
PopulateCI.groovy fails on ElectricFlow 6.0

### ISSUE THREAD

**Issue by lrochette** [electriccommunity/DSL-Samples#1]
ectool evalDsl --dslFile PopulateCI.groovy
fails with error
ectool error [InvalidScript]: Unknown exception during DSL eval at line 81: Cannot get property 'value' on null object

**Comment by gmaxey** [comment]
Workaround: add another project to the CI dashboard first.

**Comment by gmaxey** [comment]
Same as issue #4
