### ISSUE TITLE
Create plugin sample

### ISSUE THREAD

**Issue by lrochette** [electriccommunity/DSL-Samples#19]
Create an example that download a plugin from GitGub
Install it 
Promote it

**Comment by lrochette** [comment]
issue with installPlugin:

def _url = 'https://github.com/electric-cloud/EC-Admin/blob/master/EC-Admin.jar?raw=true'
def resp=installPlugin(url: _url)

Unknown exception during DSL eval at line 26: All nested operations must support requeuing: installPluginOperation does, but context[op=evalDsl,id=13350] doesn't
Line 0026: Method 'installPlugin'
Line 0026: Invoking 'installPlugin' with args {url=https://github.com/electric-cloud/EC-Admin/blob/master/EC-Admin.jar?raw=true}

**Comment by imago-storm** [comment]
This issue was moved to electric-cloud-community/DSL-Samples#11
